//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ListOrders = new HashSet<ListOrders>();
        }
    
        public int id_Order { get; set; }
        public Nullable<int> id_Clients { get; set; }
        public Nullable<int> id_Cooks { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Cooks Cooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOrders> ListOrders { get; set; }
    }
}
